version: '3.9'
services:
  minio:
    image: minio/minio
    container_name: picvault-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: picvault
    ports:
      - '5433:5432'

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 4000
      FRONTEND_ORIGIN: http://localhost:3000
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_BUCKET: picvault
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: picvault
    depends_on:
      - db
      - minio
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: https://localhost:4000/api
    depends_on:
      - backend
    ports:
      - '3000:80'
